"""empty message

Revision ID: 47b96d372f02
Revises: 0c34584c5d89
Create Date: 2020-09-15 15:04:53.526675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b96d372f02'
down_revision = '0c34584c5d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('poll_composite_id', 'Poll', ['poll_key', 'discord_server_id'])
    op.create_unique_constraint(None, 'Poll', ['discord_message_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Poll', type_='unique')
    op.drop_constraint('poll_composite_id', 'Poll', type_='unique')
    # ### end Alembic commands ###
