"""empty message

Revision ID: 56ff1fe34628
Revises: 401185a6941b
Create Date: 2019-04-19 11:35:18.984374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ff1fe34628'
down_revision = '401185a6941b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ClosedPoll', 'server_id', new_column_name='discord_server_id', existing_type=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ClosedPoll', 'discord_server_id', new_column_name='server_id', existing_type=sa.String())
    # ### end Alembic commands ###
