"""empty message

Revision ID: 5e205bb49ef5
Revises: 5586bb95d6c7
Create Date: 2019-03-18 15:18:36.696495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e205bb49ef5'
down_revision = '5586bb95d6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClosedPoll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['Channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClosedPoll')
    # ### end Alembic commands ###
