"""empty message

Revision ID: 77da8e2b32b7
Revises: f3a65fc64dec
Create Date: 2019-04-27 10:09:30.299989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77da8e2b32b7'
down_revision = 'f3a65fc64dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Poll', sa.Column('closed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Poll', 'closed_date')
    # ### end Alembic commands ###
