"""empty message

Revision ID: 7fbcb82bdb07
Revises: 
Create Date: 2019-03-18 12:33:05.938375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbcb82bdb07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('delete_commands', sa.Boolean(), nullable=True),
    sa.Column('delete_all', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('Poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('multiple_options', sa.Boolean(), nullable=True),
    sa.Column('only_numbers', sa.Boolean(), nullable=True),
    sa.Column('new_options', sa.Boolean(), nullable=True),
    sa.Column('allow_external', sa.Boolean(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['Channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id')
    )
    op.create_table('Option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['Poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.String(), nullable=True),
    sa.Column('participant_mention', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['Option.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vote')
    op.drop_table('Option')
    op.drop_table('Poll')
    op.drop_table('Channel')
    # ### end Alembic commands ###
