"""Change channel id to bigint

Revision ID: 9231c70363d9
Revises: 9e933c784898
Create Date: 2020-09-15 14:38:31.711405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9231c70363d9'
down_revision = '9e933c784898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Channel', 'discord_id')
    op.add_column('Channel', sa.Column('discord_id', sa.BigInteger(), autoincrement=False, nullable=True))
    op.drop_column('Channel', 'discord_server_id')
    op.add_column('Channel', sa.Column('discord_server_id', sa.BigInteger(), autoincrement=False, nullable=True))
    op.create_unique_constraint(None, 'Channel', ['discord_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Channel', 'discord_id')
    op.add_column('Channel', sa.Column('discord_id', sa.Integer(), autoincrement=False, nullable=True))
    op.drop_column('Channel', 'discord_server_id')
    op.add_column('Channel', sa.Column('discord_server_id', sa.Integer(), autoincrement=False, nullable=True))
    op.create_unique_constraint(None, 'Channel', ['discord_id'])
    # ### end Alembic commands ###
