"""empty message

Revision ID: 9c9bb0dd1fca
Revises: 7fbcb82bdb07
Create Date: 2019-03-18 12:49:18.166050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9bb0dd1fca'
down_revision = '7fbcb82bdb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Option', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Option', 'locked')
    # ### end Alembic commands ###
