"""Change channel id type

Revision ID: 9e933c784898
Revises: 32d96f0c50ee
Create Date: 2020-09-15 14:10:48.780343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e933c784898'
down_revision = '32d96f0c50ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Channel', 'discord_id')
    op.add_column('Channel', sa.Column('discord_id', sa.Integer(), autoincrement=False, nullable=True))
    op.drop_column('Channel', 'discord_server_id')
    op.add_column('Channel', sa.Column('discord_server_id', sa.Integer(), autoincrement=False, nullable=True))
    op.create_unique_constraint(None, 'Channel', ['discord_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Channel', 'discord_id')
    op.add_column('Channel', sa.Column('discord_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Channel', 'discord_server_id')
    op.add_column('Channel', sa.Column('discord_server_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(None, 'Channel', ['discord_id'])
    # ### end Alembic commands ###
