"""empty message

Revision ID: c7aa1b681b83
Revises: 5e205bb49ef5
Create Date: 2019-03-18 16:37:00.988468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7aa1b681b83'
down_revision = '5e205bb49ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClosedPoll', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClosedPoll', 'date')
    # ### end Alembic commands ###
