"""empty message

Revision ID: efd984e900bd
Revises: c7aa1b681b83
Create Date: 2019-03-25 14:19:19.583158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd984e900bd'
down_revision = 'c7aa1b681b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Poll', sa.Column('created_datetime', sa.DateTime(), nullable=True))
    op.add_column('Vote', sa.Column('vote_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Vote', 'vote_datetime')
    op.drop_column('Poll', 'created_datetime')
    # ### end Alembic commands ###
