"""empty message

Revision ID: f3a65fc64dec
Revises: 56ff1fe34628
Create Date: 2019-04-27 09:39:59.883867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a65fc64dec'
down_revision = '56ff1fe34628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClosedPoll')
    op.add_column('Channel', sa.Column('discord_server_id', sa.String(), nullable=True))
    op.alter_column('Option', 'option', new_column_name='option_text', existing_type=sa.String())
    op.add_column('Poll', sa.Column('closed', sa.Boolean(), nullable=True))
    op.alter_column('Poll', 'author', new_column_name='discord_author_id', existing_type=sa.String())
    op.alter_column('Poll', 'message_id', new_column_name='discord_message_id', existing_type=sa.String())
    op.alter_column('Poll', 'poll_id', new_column_name='poll_key', existing_type=sa.String())
    op.create_unique_constraint('poll_composite_id', 'Poll', ['poll_key', 'discord_server_id'])
    op.drop_constraint('Poll_poll_id_key', 'Poll', type_='unique')
    op.create_unique_constraint(None, 'Poll', ['discord_message_id'])
    op.alter_column('Vote', 'participant_id', new_column_name='discord_participant_id', existing_type=sa.String())
    op.alter_column('Vote', 'participant_mention', new_column_name='discord_participant_mention', existing_type=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Vote', 'discord_participant_id', new_column_name='participant_id', existing_type=sa.String())
    op.alter_column('Vote', 'discord_participant_mention', new_column_name='participant_mention', existing_type=sa.String())
    op.drop_constraint(None, 'Poll', type_='unique')
    op.create_unique_constraint('Poll_poll_id_key', 'Poll', ['poll_id'])
    op.drop_constraint('poll_composite_id', 'Poll', type_='unique')
    op.alter_column('Poll', 'poll_key', new_column_name='poll_id', existing_type=sa.String())
    op.alter_column('Poll', 'discord_message_id', new_column_name='message_id', existing_type=sa.String())
    op.alter_column('Poll', 'discord_author_id', new_column_name='author', existing_type=sa.String())
    op.drop_column('Poll', 'closed')
    op.alter_column('Option', 'option_text', new_column_name='option', existing_type=sa.String())
    op.drop_column('Channel', 'discord_server_id')
    op.create_table('ClosedPoll',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ClosedPoll_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('discord_server_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['Channel.id'], name='ClosedPoll_channel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ClosedPoll_pkey'),
    sa.UniqueConstraint('poll_id', name='ClosedPoll_poll_id_key')
    )
    # ### end Alembic commands ###
